[build]
  functions = "functions"  # Points to the 'functions' directory for serverless functions
  publish = "public"       # Tells Netlify to serve static assets from the 'public' folder

[[redirects]]
  from = "/products.csv"
  to = "/products.csv"
  status = 200
